### ISSUE TITLE
Fails to init camera

### ISSUE THREAD

**Issue by mmphego** [lemariva/micropython-camera-driver#1]
Hi,
I just flashed my ESP32-CAM with your custom firmware and it fails to initialise the camera, with the message display below.
Please help.

![image](https://user-images.githubusercontent.com/7910856/85630060-4c8c9f80-b673-11ea-98bd-6590df096c36.png)

Thanks in advance.

**Comment by mmphego** [comment]
When I try to re-init the esp reboots.

![image](https://user-images.githubusercontent.com/7910856/85630268-a3927480-b673-11ea-9f02-b139d976cfaf.png)

**Comment by lemariva** [comment]
Just ignore the error (GPIO isr service already installed), it is related with this [PR](https://github.com/espressif/esp32-camera/pull/145). The camera works without any problem.
If you try to initiate the camera twice, the board reboots. But as I said, initiate the camera once and ignore the error.

**Comment by lemariva** [comment]
No, I used the code to get still images (timelapse), but you can check this [fork](https://github.com/krayon/upyesp32cam/commit/8b63edec50dca9416bb4b2b75207ac53788c597a), may be it helps. You need to adapt it to the new driver.

**Comment by mmphego** [comment]
Thanks and keep those blog post coming.
I have bookmarked your page.

**Comment by lemariva** [comment]
FYI, the streaming mode works. I added it to the master branch. You need to set a get parameter `stream=true` and you get a MPEG streaming. I've just updated the firmware to make it compatible to the application.

**Comment by mmphego** [comment]
> FYI, the streaming mode works. I added it to the master branch. You need to set a get parameter `stream=true` and you get a MPEG streaming. I've just updated the firmware to make it compatible to the application.

How many fps on average?

**Comment by lemariva** [comment]
very low: 2 fps

**Comment by mmphego** [comment]
I got the same results, dissapointed. Had to end up using Arduino.
Thanks Mauro
