### ISSUE TITLE
Other image formats?

### ISSUE THREAD

**Issue by Skipper-is** [lemariva/micropython-camera-driver#11]
I'm trying to get this to interface with a thermal printer, that takes bitmaps, and in the absence of PIL on Micropython (or similar image handling packages), I'm a little stuck converting from jpeg to bitmap. Is there a way of shooting in other formats with the camera? I've tried format=camer.GRAYSCALE, but that doesn't seem to be a format...

**Comment by lemariva** [comment]
There are 4 formats available (camera.GRAYSCALE, camera.JPEG, camera.RGB565, camera.YUV422). However, the board running mp has limited RAM. So you should use a small frame size while using formats other than JPEG. I've updated the driver to include the framesize as parameter for the `init` function.
