### ISSUE TITLE
while conecting to wifi starts to boot loop

### ISSUE THREAD

**Issue by RKS200** [lemariva/micropython-camera-driver#25]
while passing station.connect(arg**)

**Comment by 404menotfound** [comment]
You have a power supply problem, probably. ESP32 has something called "Brownout protection". This is a hardware feature that shuts down the processor if the system voltage is below a threshold. Enabling WiFi, causes the system to halt and reboot.

**Comment by lemariva** [comment]
@404menotfound is right. Check the code on a new board.
