### ISSUE TITLE
Camera XRZ00D1 V240

### ISSUE THREAD

**Issue by Jctarin** [lemariva/micropython-camera-driver#26]
I am using the ESP32-CAM with the XRZ00D1 V240 camera module and it does not work when I try to capture images.

**Comment by lemariva** [comment]
Are the camera modules compatible and the XRZ00D1 V240 uses the same pin layer? I'm afraid, I can only say that it works with the modules that I've tested. There are a lot of china OV2460 boards / cameras and I don't have all of them.
