### ISSUE TITLE
Feature request: Set camera sensor values

### ISSUE THREAD

**Issue by joerggollnick** [lemariva/micropython-camera-driver#3]
My sensor in T-Camera Mini need some additional config like vflip may be hmirror.

My idea is to add a new function 

def set( vflip = None, hmirror = None, brightness = None, saturation = None,  framesize = None ):

Reference could be:
 https://github.com/Xinyuan-LilyGO/TTGO_Camera_Mini/blob/master/TTGO_Camera_Mini.ino Line 151

But my skills to write a C extensions for micropython are limited to read (C and python) code.

**Comment by joerggollnick** [comment]
Provided a pull request #4 for this also.

**Comment by lemariva** [comment]
Thanks! I've just merged the PR and updated the MP version.
