### ISSUE TITLE
urequests module unavailable

### ISSUE THREAD

**Issue by ani-rudh** [lemariva/micropython-camera-driver#31]
Hi,
I need to make a https request from my uPy code and I see that the urequests model is missing. Is there something I am missing or has anyone successfully used the module to make https requests using this firmware?

I tried installing the module seperatley but it unfortunately doesn't support https requests. I tried by flashing the official micropython firmware v1.17 and it works on that version.

Therefore, I am trying to follow the DIY approach to flash the firmware with camera support in order to use the latest firmware that has urequests working. Unfortunately it is not clear to follow the instructions, especially the steps here:

![diy_steps_esp32cam](https://user-images.githubusercontent.com/15331399/133235683-62d78592-5709-46c8-acff-61c5152f1cd8.png)

Should I use the https://github.com/lemariva/esp32-camera repo or the git clone https://github.com/espressif/esp32-camera in the components folder?

In the following steps, from the instructions [here](https://lemariva.com/blog/2020/03/tutorial-getting-started-micropython-v20), what needs to be done after adding the PATH variables to install the idf?

![Screenshot from 2021-09-14 11-50-53](https://user-images.githubusercontent.com/15331399/133237911-e3f28857-5606-4198-9efc-f583c2f92248.png)

Since I am not very familiar with the usage of these tools and compiling the firmware, excuse me if the queries are trivial!

Thank you in advance,
Ani

**Comment by lemariva** [comment]
Sorry for that, it was the https://github.com/lemariva/esp32-camera not the official one that had a bug. Anyways, today I've updated the building guide (readme and link) and the firmware. Check them out!
* [MicroPython: Updated support for cameras: M5CAMERA, ESP32-CAM etc.](https://lemariva.com/blog/2022/01/micropython-upgraded-support-cameras-m5camera-esp32-cam-etc)
