### ISSUE TITLE
camera not working on new compiling

### ISSUE THREAD

**Issue by skeyvin** [lemariva/micropython-camera-driver#33]
followed the compiling instructions and got it on the esp
but when i import `OSError: Camera Init Failed`
any fix?

**Comment by lemariva** [comment]
check the new firmware if it works. You didn't mention the board, but check also the pin layer of it.

**Comment by skeyvin** [comment]
enabled the os debugs and got error 0x105
and the pin layout seems to be not for ai thinkers module
what are the pins for that?
